# syntax=docker/dockerfile:1

# -----------------------------------------------------------------------------
# BUILD
# -----------------------------------------------------------------------------

FROM node:24-bookworm-slim AS build

WORKDIR /build

# Dépendances d'abord pour profiter du cache Docker.
COPY web/package.json web/package-lock.json ./

RUN npm ci

COPY web/ ./

RUN npm run build


# -----------------------------------------------------------------------------
# RUNTIME
# -----------------------------------------------------------------------------

FROM nginxinc/nginx-unprivileged:1.30.4-alpine3.24

COPY .docker/web/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /build/dist/ /usr/share/nginx/html/

EXPOSE 8080
